version: "3.9"
services:
  runner:
    restart: unless-stopped
    # The hostname is what Github will identify your runner as.
    hostname: <hostname>
    build:
      context: build
      dockerfile: Dockerfile
    volumes:
      - "./work:/root/runner:rw"
      # Uncomment this if you want to enable docker in docker support
      #- "/var/run/docker.sock:/var/run/docker.sock:rw"
    environment:
    # These can be removed after the first run
    - "GITHUB_TOKEN=<token>"
    - "GITHUB_REPOSITORY=<repository>"