name: Publish Void Linux Image

on:
  schedule:
    # Run every Sunday at 12:45 PM UTC
    - cron: '45 12 * * 0'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish Release
    runs-on: self-hosted
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build Void Linux
        run: |
          cd ${{ github.workspace }}/libs/void-docker
          docker buildx build -f Dockerfile.full -t void-linux --build-arg "BOOTSTRAP_VERSION=latest-x86_64-musl" .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/build
          file: build/Dockerfile
          push: true
          tags: ghcr.io/oolunar/githubdockerrunner:latest