name: Publish Void Linux Image

on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

jobs:
  publish:
    name: Publish Release
    runs-on: self-hosted
    permissions: write-all
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build Void Linux
        run: |
          cd ${{ github.workspace }}/libs/void-docker
          docker buildx build -f Dockerfile.full -t void-linux --build-arg "BOOTSTRAP_VERSION=latest-x86_64-musl" .
      - name: Build Github Docker Runner
        run: |
          cd ${{ github.workspace }}/build
          docker buildx build -t "ghcr.io/oolunar/githubdockerrunner:latest" -t "ghcr.io/oolunar/githubdockerrunner:${{ github.sha }}" .
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/oolunar/githubdockerrunner:latest
            ghcr.io/oolunar/githubdockerrunner:${{ github.sha }}